open -> opens file

try:
exception:
else: - no exception occurred 
finally:

raise -> throw 
	NameEror("")
	ValueEror
	
also have garbage collector / not explained jet, when it starts

  

function and parameters -> magic find on-line